services:
  - type: web
    name: ytdlp-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_USER
        sync: false
      - key: APP_PASSWORD
        sync: false
    healthCheckPath: /api/health
